name: Claude Code Action

on:
  issue_comment:
    types: [created, edited]
  pull_request_review_comment:
    types: [created, edited]

permissions:
  contents: read
  issues: write
  pull-requests: write
  id-token: write

jobs:
  claude-action:
    if: contains(github.event.comment.body, '@claude')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: grll/claude-code-action@main
        with:
          access_token: ${{ secrets.CLAUDE_ACCESS_TOKEN }}
          refresh_token: ${{ secrets.CLAUDE_REFRESH_TOKEN }}
          expires_at: ${{ secrets.CLAUDE_EXPIRES_AT }}
          secrets_admin_pat: ${{ secrets.SECRETS_ADMIN_PAT }}